---
- name: Install {{ mysql_packages }}
  yum:
    name: "{{ mysql_packages }}"
    state: present
#
- name: Start {{ mysql_service }}
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: true
...
